### PR TITLE
Fix issue #1139: DataProvider supports Object[] and Iterator<Object> as a valid return types

### PR DESCRIPTION
**Pull request by juherr**
To review commit by commit

### CODE REVIEW

**Comment by juherr** [comment]
Ping @cbeust

**Comment by cbeust** [comment]
75 files changed, a thousand new lines of code... you're killing me :-)

I took a quick look at the main business logic since most of it seems to be test, LGTM.

**Comment by juherr** [comment]
:) 

The priority is the first commit with business logic. 
The second one is just a rewrite of tests like previous pull requests. Less risky IMO.

**Comment by juherr** [comment]
Ping @cbeust

**Comment by cbeust** [comment]
Sorry I finished reviewing it yesterday, looks good.

**Comment by juherr** [comment]
Not a problem. I just fixed the merge conflict today ;)

**Comment by nitinverma** [comment]
Iterable should be preferred as the framework may need to iterate more than once. if not today tomorrow.

**Pull request merged**
