### PR TITLE
Adding Retry scenario details to report to Fix #2180

### LINKED ISSUE #2180: Write details for all test scenarios including Retried tests
### Expected behavior
We should write details for all test scenarios including retried tests in report. 

### Actual behavior
Currently scenario details are written for Passed, Failed, Skipped (including configuration results). But scenario details for retried tests are missing.

In TestNG report, When we click on hyperlink for any of the retried tests, it just redirects to a wrong test method as we didn't write retried tests.

### PR DESCRIPTION
**Pull request by kdevendraraju**
Fixes #Adding Retry scenario details to report .

Updated `writeScenarioDetails()` to display retried tests scenario details in testng report.

### Did you remember to?

- [x] Update `CHANGES.txt`

### CODE REVIEW

**Comment by krmahadevan** [comment]
@kdevendraraju - Two things.

1. You need to fix the merge conflicts.
2. Can you please share a screenshot of how the new report with the details would look like, along with a comparison of how it currently looks like? That will help us see the diff a bit more easily

**Review by juherr — APPROVED** [review]

**Comment by juherr** [comment]
@krmahadevan LGTM. Just "squash and merge" if ok for you too :)

**Comment by krmahadevan** [comment]
@juherr - Sure will do.. There is a merge conflict in this and also I was hoping that I could see a diff of how the previous and new report looks like as screenshot..

**Comment by kdevendraraju** [comment]
@krmahadevan 

Below is the example code that I worked on 

`package com.test;

import org.testng.Assert;
import org.testng.annotations.Test;

public class TestRetry {

    @Test(retryAnalyzer = com.test.RetryAnalyzer.class)
    public void Test1()    {
        Assert.assertEquals(false, true);
    }

    @Test
    public void Test2()     {
        Assert.assertEquals(false, true);
    }
}
`

Retry listener class - 

`package com.test;

import org.testng.IRetryAnalyzer;
import org.testng.ITestResult;

public class RetryAnalyzer implements IRetryAnalyzer {

    int counter = 0;
    int retryValue = 2;

    public boolean retry(ITestResult result) {
        if(counter < retryValue) {
            counter++;
            return true;
        }
        return false;
    }
}`


Default report will only show the scenario details for both the failed tests. And when we click on retried tests (which is hyper linked) will not take us anywhere.

After adding `writeScenarioDetails(testResult.getRetriedTestResults(), scenarioIndex);` , it will show stacktrace for the retried tests also.

And also when we click on retried tests, it will take us to the retried test stacktrace.

**Old Report screenshots** - 

old_report_part_1
old_report_part_2

**New report screenshots** - 

new_report_part_1
new_report_part_2
new_report_part_3
new_report_part_4

Please let me know if anything is missing.

Thank You.

**Comment by krmahadevan** [comment]
@kdevendraraju - Can you please rebase and fix the merge conflicts so that we can get this merged ?

**Comment by kdevendraraju** [comment]
@krmahadevan 

Done. 

Please check now.

**Review by krmahadevan — APPROVED** [review]

**Pull request merged**
