### PR TITLE
Rework ReporterConfig creation

### PR DESCRIPTION
**Pull request by juherr**
Mix of #2303 and #2306 with https://github.com/cbeust/testng/commit/f41210ed6f7983fa48249b402cffcdf99652219b added

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - There are still merge conflicts here. Did you rebase this PR off of `upstream/master` ?

**Comment by juherr** [comment]
@krmahadevan Updated. And it should be reviewable now :)

Another view can be: https://github.com/sbabcoc/testng/compare/pr/fix-reporter-deserialize...juherr:sbabcoc-pr/fix-reporter-deserialize

**Comment by krmahadevan** [comment]
@juherr - Which would need to be looked at ? Is it #2307 (or) #2303 ? Because @sbabcoc has updated #2303 with review comments and then you have created this PR. So a bit confused.

**Comment by juherr** [comment]
@krmahadevan I rebased the branch and I'm waiting for feedback. The same PR is there: https://github.com/sbabcoc/testng/pull/2

**Review by krmahadevan — APPROVED** [review]
@juherr - This changeset looks good to me. Shall we go ahead and merge this and ignore the other one ( #2303 that @sbabcoc raised) ?

**Comment by juherr** [comment]
Both are merged because Github considers this one is #2303 + some extra commits.

**Pull request merged**
