### PR TITLE
Fix issues #169 and #171 : Only register one instance for suite listener and invoked method listener

### PR DESCRIPTION
**Pull request by juherr**

### CODE REVIEW

**Comment by lqc** [comment]
Doesn't this change the order in which the listeners are executed (because
of the hash map) ?

-- 
Łukasz Rekucki

**Comment by juherr** [comment]
Maybe but the documentation doesn't specify an order on listeners nor order between all the ways to specify them.

Maybe you could share your need and explain why order should be important?

**Comment by cbeust** [comment]
Yes, I never specified that listeners were run in a specific order. @lqc you're right that @juherr's fix changes that but it shouldn't break anyone.

It's possible to introduce ordering on top of Julien's patch but this should be 1) properly justified (do you have a good use case?) and 2) done in a separate PR.

I don't really feel it's very important, personally: if you need ordering, you can just add one listener and order things the way you want them in it.

**Comment by nemesis13** [comment]
Big thanks for this @juherr.

Speaking of the SuiteRunner, what do you guys think about getters and removal methods for the listeners? I'm facing a problem where I need a different IInvokedMethodListener instance per test class and using the current implementation I can't do that in a clean way (see #791). Having this feature I could at least implement a workaround.

**Pull request merged**
