### PR TITLE
Issue #1430 : Fix loading class from file with ant and classfileset

### LINKED ISSUE #1430: Cannot load class from file  XXX when using with ant and classfileset
### Expected behavior
The class shall be found in classpath

### Actual behavior
The class is not found

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [X] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

Not tested on others
 
### Test case sample

In ant file

        <path id="test.classpath">
            <pathelement location="test/lib/testng-6.11.jar" />
            <pathelement location="test/lib/jcommander-1.64.jar" />
            <pathelement location="test/classes" />
        </path>

        <testng classpathref="test.classpath" outputdir="test/reports"> 
           <classfileset dir="test/classes"> 
           	 <include name="**/Test*.class"/>
           </classfileset>
        </testng>

In java file (TestNgSample.java)

```java
import org.testng.Assert;
import org.testng.annotations.Test;

public class TestNgSample {
	@Test
	public void testTrue() {
		Assert.assertTrue(true);
	}
}
```

### PR DESCRIPTION
**Pull request by mourezwell**
Fixes #1430  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

### CODE REVIEW

**Comment by juherr** [comment]
@mourezwell Thanks for the PR. Could you just explain the change? It looks it fixes the classpath issue but I fear it will add some other issues which are not yet tested.

**Comment by mourezwell** [comment]
Hello,

My change has fixed the class search from class file path

For ex : input path is c:\toto\tata\src\main\java\com\test\Example.class

the path is split by / or \ then

before code was looking for
Example.class, => not found (missing package info) then for
Example.classtest.Example.class => not found (package info build badly)
then  for
Example.classtest.Example.classcom.Example.classtest.Example.class => not
found then (...)

after code is looking for
Example.class, => not found (missing package info) then for
test.Example.class => not found (package info not complete) then for
com.test.Example.class => found (full name ok)

The problem was the bad use of StringBuilder that can not be used to
prepend strings

The impact is not only for ant runner, it is for all runner that uses test
class définition instead of xml test suite definition (applies to maven or
command lines)

I did not impact the classpath a priori.

Regards,

Olivier

**Review by juherr — APPROVED** [review]
LGTM 👍 
Ping @cbeust

**Comment by cbeust** [comment]
Took me a few reads to understand where the bug was but I see it now :-)

**Pull request merged**
