### PR TITLE
Sonar cube violation fix.

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes # .

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - This PR fixes the [sonarcube violations](https://sonarqube.com/issues/search#projectUuids=3bfc5973-13be-4784-b59f-c650d118898b|assignees=krmahadevan%40github|createdAt=2017-02-27T20%3A32%3A36%2B0100) that were introduced by me.

**Review by juherr — APPROVED** [review]
LGTM 👍 

Ping @cbeust

**Comment by cbeust** [comment]
I'm not crazy about the specific violations listed here (complexity, indentation, etc...) but well.

Let's not go too far with these.

**Comment by krmahadevan** [comment]
@cbeust - I remember those comments from a previous PR that I submitted :) But since this violation was due to my delivery and sonarcube assigned them to me, I thought I would go ahead and fix them.

**Comment by juherr** [comment]
We can discuss forever about sonar rules. And they are helpful most of the time IMO.

I'd love to have sonar as reviewer of pull requests but it didn't work the last time I tried.

But +1 to be pragmatic with them.

**Comment by juherr** [comment]
Ping @cbeust

**Pull request merged**
