### PR TITLE
Ensure TestResult contains proper test method

### LINKED ISSUE #1061: Feature request: Have a way to change timeout dynamically at runtime
From: http://stackoverflow.com/q/37722712/4234729

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1061

When natively injecting a ITestResult for a configuration method
TestNG doesn’t inject the correct test method.
Fixed this, so that user’s can leverage native 
injection of ITestResult and do things such as 
altering timeouts of the method to be executed etc.,

Fixes #1061 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr - Please help take a look

**Comment by juherr** [comment]
@krmahadevan GitHub is already sending me an email when you add me as reviewer, so you don't need to ping me unless I take too much time to review ;)

**Review by juherr — APPROVED** [review]
LGTM 👍

**Comment by krmahadevan** [comment]
@juherr - My bad. Old habits die hard. I am used to pinging you for review request. I keep forgetting the part that a review request is an automatic ping. I will refrain from doing that going forward :)
Regret the inconvenience.

**Pull request merged**
