### PR TITLE
Set suitethreadpoolsize

### PR DESCRIPTION
**Pull request by dundacek**
... for suites can be run in parallel using maven surefire

### CODE REVIEW

**Comment by dundacek** [comment]
Parallel TestNG test suites still can not be run by Maven surefire. I googled this:
https://github.com/emillan26/testng/commit/a60ad7cac6c3c302b578a60f75a2be7468b4532f
https://groups.google.com/forum/#!topic/testng-dev/osweiO53cig

**Comment by cbeust** [comment]
Thanks. Can you update the CHANGES file too for the release notes?

**Comment by Tibor17** [comment]
Without this fix maven-surefire-plugin is not expected to work?
I can check it out with TestNG 6.9.6 but not with this snapshot.
We made a fix in Surefire which sends this option down to TestNG, but I am not allowed to release it unless TestNG makes the release. When is your release planned?

**Comment by Tibor17** [comment]
@dundacek 
@cbeust 
When you plan release of Version 6.9.7?

**Pull request merged**
