### PR TITLE
Bump gradle version to 7.3.3 to support java17 build

### PR DESCRIPTION
**Pull request by hezhangjian**
### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`
- [x] Auto applied styling via `./gradlew autostyleApply`

### CODE REVIEW

**Comment by krmahadevan** [comment]
@Shoothzj - all the tests failed. Can you please check ?

**Comment by Shoothzj** [comment]
> @Shoothzj - all the tests failed. Can you please check ?

Since I am first contributor, can't manualy check tests.
Sorry for using wrong checksum of gradle. 
Fixed

**Comment by Shoothzj** [comment]
@krmahadevan Shoud I retry the tests? :)
Thanks for your help

**Review by krmahadevan — APPROVED** [review]
@juherr - Once you are fine with the changes, can we merge this PR?

**Comment by krmahadevan** [comment]
> @krmahadevan Shoud I retry the tests? :) Thanks for your help

@Shoothzj - Nah. We are good. We have some flaky tests in the codebase (which need to be fixed and doesn't have anything to do with your PR). Thank you so much for taking the time to raise this PR. Appreciate it and hope to see more contributions coming from you 👍

**Review by juherr — APPROVED** [review]

**Pull request merged**
