### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by juherr**

### CODE REVIEW

**Review by krmahadevan — COMMENTED** [review]
@juherr  do we really need to be deleting `CONTRIBUTING.md` since I thought its contents would still be useful for first time contributors.

**Comment by juherr** [comment]
@krmahadevan Right but it is a duplicate file of https://github.com/cbeust/testng/blob/master/.github/CONTRIBUTING.md

**Comment by krmahadevan** [comment]
> @krmahadevan Right but it is a duplicate file of https://github.com/cbeust/testng/blob/master/.github/CONTRIBUTING.md

@juherr  only the file names are same. Contents are different. Maybe we can move the contents of this file as well into that one ?

**Comment by juherr** [comment]
> @juherr only the file names are same. Contents are different. Maybe we can move the contents of this file as well into that one ?

That was my first intention but the gradle instructions are deprecated and I supposed the best practices are well known and common now.

**Pull request merged**
