### PR TITLE
Inject context in parent module

### PR DESCRIPTION
**Pull request by juherr**
Sometimes we need the context in order to configure the parent module.

### CODE REVIEW

**Comment by cbeust** [comment]
Thanks, Julien!

**Comment by VladRassokhin** [comment]
@cbeust besides sources are Java 7 now, target platform will still be Java 5 at least for TestNG 6.x branch?

**Comment by cbeust** [comment]
I don't know, at this point I feel ready to just deprecate Java 5 and 6
support.


-- 
Cédric

**Comment by drapostolos** [comment]
+1

**Pull request merged**
