### PR TITLE
Add JIT randomization options for increasing CI coverage

### PR DESCRIPTION
**Pull request by vlsi**
By default, JIT compiler is predictable, so adding randomization during the tests might reveal "missing volatile", "missing synchronized", and similar cases.

Non-randomized jobs are still there, so we don't miss testing "production-like" configuration :)

Inspiration source: https://twitter.com/VladimirSitnikv/status/1405578893168463877

### CODE REVIEW

**Review by juherr — APPROVED** [review]

**Comment by vlsi** [comment]
It seems to work, it does not make CI time slower, so I think it can be merged.

**Review by krmahadevan — APPROVED** [review]

**Comment by juherr** [comment]
@vlsi Any idea why tests are not run in some cases? See warnings from https://github.com/cbeust/testng/actions/runs/949595738

**Comment by vlsi** [comment]
Oh, there's unexpected logging (the same message duplicates a lot :( ):

```
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
Warning:  set +LogCompilation to log the seed.
```

**Comment by vlsi** [comment]
@juherr , what do you mean by "not run"?

I do not understand what the following failure means, and it might be related to a true bug:

ParallelByMethodsTestCase1Scenario2.verifyThatTestMethodsRunInParallelThreads

```
java.lang.AssertionError: Expected 13 test method start event logs to be in a block of methods executing in parallel. Found an event log of a different type in the block being processed:

[EventLog{Event: LISTENER_TEST_METHOD_START, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassDThreeMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodA, Time of event: 2021-06-18 10:58:49.967, Thread ID: 5385},
EventLog{Event: LISTENER_TEST_METHOD_START, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassDThreeMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodB, Time of event: 2021-06-18 10:58:49.967, Thread ID: 5386},
EventLog{Event: LISTENER_TEST_METHOD_START, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassDThreeMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodC, Time of event: 2021-06-18 10:58:49.967, Thread ID: 5387},
EventLog{Event: LISTENER_TEST_METHOD_START, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassBFourMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodA, Time of event: 2021-06-18 10:58:49.968, Thread ID: 5388},
EventLog{Event: LISTENER_TEST_METHOD_START, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassBFourMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodB, Time of event: 2021-06-18 10:58:49.968, Thread ID: 5389},
EventLog{Event: LISTENER_TEST_METHOD_START, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassBFourMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodC, Time of event: 2021-06-18 10:58:49.968, Thread ID: 5390},
EventLog{Event: LISTENER_TEST_METHOD_START, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassBFourMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodD, Time of event: 2021-06-18 10:58:50.301, Thread ID: 5391},
EventLog{Event: TEST_METHOD_EXECUTION, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassDThreeMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodC, Time of event: 2021-06-18 10:58:50.496, Thread ID: 5387},
EventLog{Event: TEST_METHOD_EXECUTION, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassDThreeMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodB, Time of event: 2021-06-18 10:58:50.496, Thread ID: 5386},
EventLog{Event: TEST_METHOD_EXECUTION, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassDThreeMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodA, Time of event: 2021-06-18 10:58:50.496, Thread ID: 5385},
EventLog{Event: TEST_METHOD_EXECUTION, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassBFourMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodC, Time of event: 2021-06-18 10:58:50.496, Thread ID: 5390},
EventLog{Event: TEST_METHOD_EXECUTION, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassBFourMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodB, Time of event: 2021-06-18 10:58:50.496, Thread ID: 5389},
EventLog{Event: TEST_METHOD_EXECUTION, Suite: TestSuiteB, Test: TestSuiteB-ThreeTestClassTest, Class: test.thread.parallelization.sample.TestClassBFourMethodsWithNoDepsSample, Class instance hash code: 1, Method name: testMethodA, Time of event: 2021-06-18 10:58:50.496, Thread ID: 5388}] expected [true] but found [false]	
at org.testng.Assert.fail(Assert.java:110)
```

**Comment by vlsi** [comment]
Just for the reference, "to log the seed" output was removed for 17 in https://github.com/openjdk/jdk/pull/1863

**Comment by juherr** [comment]
@vlsi I am missing something:

* WARNING: `8, Zulu, macos, Pacific/Chatham, tr_TR` => no test output
* WARNING: `8, Zulu, ubuntu, America/New_York, tr_TR, stress JIT` => test output
* WARNING: `11, Adopt OpenJ9, ubuntu, Pacific/Chatham, fr_FR` => test output
* `11, Adopt OpenJ9, windows, America/New_York, tr_TR` => no test output
* `16, Adopt OpenJ9, ubuntu, Pacific/Chatham, de_DE` => test output
* FAILURE: `16, Zulu, same hashcode, windows, America/New_York, tr_TR, stress JIT` => test ouput wit failure of `test.thread.parallelization.ParallelByMethodsTestCase1Scenario2 > verifyThatTestMethodsRunInParallelThreads`
* WARNING: `16, Zulu, ubuntu, Pacific/Chatham, ru_RU` => no test output

I don't understand:
* why there are 3 failures instead of only 1
* why there are warnings
* why the tests are not always run (the duration of the task is another clue)

**Comment by vlsi** [comment]
> WARNING: 8, Zulu, macos, Pacific/Chatham, tr_TR => no test output

GitHub Actions currently support only `warning` and `error` markers (https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message)

"Gradle Build Scan: https://gradle.com/s/hbhz4xbjksmzg" is printed as a warning so build scans are easily accessible without browsing the log (see `gradle-build-scan-report ` option in https://github.com/burrunan/gradle-cache-action/)

---

> why there are 3 failures instead of only 1

One is for "test X" failed, the second is "there are failing tests", and the third one is "Gradle execution failed".
I agree "text X failed" is enough if "there are failing tests" and "Gradle execution failed" are the consequence of the failed test X. However, there are cases like "test X failed", and "Gradle execution failed due to NPE in Gradle".

If you want to reduce warnings to 1, you are welcome to https://github.com/vlsi/vlsi-release-plugins/blob/master/plugins/gradle-extensions-plugin

---

> why the tests are not always run (the duration of the task is another clue)

The tests are cached into Gradle Build Cache, so if they are run with the same code in the same JVM, then they are not re-executed.

For instance, if you do not edit `testng-assert` code, then why re-execute tests?

**Comment by juherr** [comment]
> > WARNING: 8, Zulu, macos, Pacific/Chatham, tr_TR => no test output
> 
> GitHub Actions currently support only `warning` and `error` markers ([docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message))
> 
> "Gradle Build Scan: [gradle.com/s/hbhz4xbjksmzg](https://gradle.com/s/hbhz4xbjksmzg)" is printed as a warning so build scans are easily accessible without browsing the log (see `gradle-build-scan-report ` option in [burrunan/gradle-cache-action](https://github.com/burrunan/gradle-cache-action/))

Ok for the warning except we should have it everywhere, right?

> > why there are 3 failures instead of only 1
> 
> One is for "test X" failed, the second is "there are failing tests", and the third one is "Gradle execution failed".
> I agree "text X failed" is enough if "there are failing tests" and "Gradle execution failed" are the consequence of the failed test X. However, there are cases like "test X failed", and "Gradle execution failed due to NPE in Gradle".
> 
> If you want to reduce warnings to 1, you are welcome to [https://github.com/vlsi/vlsi-release-plugins/blob/master/plugins/gradle-extensions-plugin](https://github.com/vlsi/vlsi-release-plugins/blob/master/plugins/gradle-extensions-plugin?rgh-link-date=2021-06-18T13%3A28%3A10Z)

Ok, got it!
 
> > why the tests are not always run (the duration of the task is another clue)
> 
> The tests are cached into Gradle Build Cache, so if they are run with the same code in the same JVM, then they are not re-executed.
> 
> For instance, if you do not edit `testng-assert` code, then why re-execute tests?

I understand that but every case of the matrix is different and we want to check the behavior of the tests.
Even if the bytecode is the same, not running tests every time may produce a false positive, right?

**Comment by vlsi** [comment]
>Even if the bytecode is the same, not running tests every time may produce a false positive, right?

Why's that?
Can you give an example?

**Comment by juherr** [comment]
For example not test run for `11, Adopt OpenJ9, windows, America/New_York, tr_TR`.
Is this exact use case was already tested with the exact same base code?

**Comment by krmahadevan** [comment]
Can we not just have gradle execute all tests all the time against all VM irrespective of whether there was a code change or not. We are not going to be gaining anything by skipping some tests due to the caching logic and at the same time we are not going to be losing anything just because a few more tests ran.

**Comment by vlsi** [comment]
Running irrelevant tests and re-building javadocs does take time, which makes PR testing frustrating

**Comment by juherr** [comment]
I agree building javadocs is a waste of time and should be done on only one expected target.

Why do you think some test cases are irrelevant if they can highlight some issues?

**Pull request merged**
