### PR TITLE
DataProvider improvments

### PR DESCRIPTION
**Pull request by juherr**
This PR:
- avoid the `static` limitation of external `DataProvider`;
- allow to use Guice injection.

Notice: I'm not totally proud of the implementation, so I'm open to remarks.

### CODE REVIEW

**Comment by cbeust** [comment]
Looks good overall. Do you mind adding one line to CHANGES to describe this pull request? Then I'll merge it.

Thanks!

**Comment by juherr** [comment]
Done, but I've just seen some little changes I want to add before merge. 
I will do it tomorrow :)

**Comment by cbeust** [comment]
Thanks, let me know when it's ready to be merged.

**Comment by juherr** [comment]
I think it's ready now.

**Pull request merged**
