### PR TITLE
Ignore local.properties

### PR DESCRIPTION
**Pull request by rschmitt**
This pretty clearly looks like it shouldn't be under source control. Disregard if I'm wrong, obviously.

### CODE REVIEW

**Comment by cbeust** [comment]
Correct but the publishing task needs it. Probably needs to modify `publishing.gradle` for first testing that the file exists (or `touch` it, which I thought I had asked Travis to do).

**Comment by rschmitt** [comment]
You mean publishing to Maven? Is Travis publishing to the snapshot repo currently?

**Comment by cbeust** [comment]
With Maven, I was publishing to Sonatype but with Gradle, I'm now publishing to JCenter (and deploying to Maven Central from there).

I was saying that if you delete `local.properties` (and you're right, it should not be checked in), then the task in `publishing.gradle` should be patched to not break if that file is not there. I was planning to do that at some point.

**Comment by rschmitt** [comment]
Ah, I see the issue.

**Comment by rschmitt** [comment]
Look good now?

**Pull request merged**
