### PR TITLE
Fix comment issues.

### PR DESCRIPTION
**Pull request by User253489**
Fix comment issues.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@User253489 - Can you please fix your `~/.gitconfig` file to ensure that it has a valid name and a valid email address. It currently has something like this `From: User253489<user253489@gmail.com>`. 

We would also appreciate if you could please utilize your precious time to help us by contributing to documentation perhaps (going by this PR I am guessing that you would like to take baby steps) instead of comments?  You could start by adding more verbose javadocs to the public APIs because that is still read by people.

**Review by juherr — APPROVED** [review]
Ping @cbeust

**Comment by krmahadevan** [comment]
@cbeust - Request you to please do a "rebase and merge" when applying this change.

**Comment by User253489** [comment]
@krmahadevan The name and e-mail address that are in the `~/.gitconfig` file are valid.

Thank you very much for your suggestions on how to contribute to this project.

**Pull request merged**
