### PR TITLE
2857 xml test index in yaml suite

### LINKED ISSUE #2857: XmlTest index is not set for test suites invoked with YAML
### Expected behavior
ITestResult.getTestClass().getXmlTest().getIndex() should return valid test indexes when a TestNG class is invoked from YAML test suite.

### Actual behavior
ITestResult.getTestClass().getXmlTest().getIndex() always returns 0. 
When the same test class is invoked from an XML suite, the XmlTest.getIndex() returns expected values.

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
To reproduce run the following class:

```
public class TestNGTest {
    @Parameters("input")
    @Test
    public void testSomething(String input) throws Exception {
        // doSomething
    }
    @AfterMethod
    public void afterMethod(ITestResult result) {
        XmlTest xmlTest = result.getTestClass().getXmlTest();
        System.out.println("afterMethod test=" + xmlTest.getName() + ", index=" + xmlTest.getIndex());
    }
}
```
with the YAML test descriptor:
```
name: SuiteYaml
tests:
  - name: TestYaml-1
    parameters: { input: yaml_1 }
    classes:
      - test.TestNGTest
  - name: TestYaml-2
    parameters: { input: yaml_2 }
    classes:
      - test.TestNGTest
```
observe console output with '0' test indexes:
```
afterMethod test=TestYaml-1, index=0
afterMethod test=TestYaml-2, index=0
```
Run the same class with an equivalent XML test descriptor:
```
<suite name="SuiteXml">
  <test name="TestXml-1">
    <parameter name="input" value="xml_1"/>
    <classes>
      <class name="test.TestNGTest"/>
    </classes>
  </test>
  <test name="TestXml-2">
    <parameter name="input" value="xml_2"/>
    <classes>
      <class name="test.TestNGTest"/>
    </classes>
  </test>
</suite>
```
observe console output with correct test indexes:
```
afterMethod test=TestXml-1, index=0
afterMethod test=TestXml-2, index=1
```
Presumably the following code section in the `parse` method of `org.testng.internal.Yaml` should be setting the XmlTest indexes:
```
// Adjust XmlTest parents and indices
for (XmlTest t : result.getTests()) {
    t.setSuite(result);
    int index = 0;
    for (XmlClass c : t.getClasses()) {
        c.setIndex(index++);
    }
}
```

### PR DESCRIPTION
**Pull request by sbaranov-parasoft**
Fixes #2857.

Set XmlTest indexes after loading test suite from Yaml.

### CODE REVIEW

**Review by krmahadevan — CHANGES_REQUESTED** [review]
Can you please help add a test that validates this as well ?

**Review by juherr — COMMENTED** [review]
Will be good with a non regression test 👍

**Comment by sbaranov-parasoft** [comment]
Yes, sure, I'll be adding a test shortly.

**Comment by krmahadevan** [comment]
> Yes, sure, I'll be adding a test shortly.

@sbaranov-parasoft - It would be good if you could please help add the test asap because we plan to release `7.7.1` as a bug fix release over the weekend. So if this PR gets merged, then your change also would be available for use via this bugfix release.

**Comment by sbaranov-parasoft** [comment]
I might not be able to do it by the time you mentioned. More likely next week.

**Review by juherr — APPROVED** [review]

**Comment by juherr** [comment]
Hi, sorry for the delay of the review.
Could you rebase in order to make it mergeable?

**Comment by krmahadevan** [comment]
> Hi, sorry for the delay of the review. Could you rebase in order to make it mergeable?

@juherr - I went ahead and then rebased this branch off of `master` and squashed the commits as well. Once the CI runs to completion, I will go ahead and get this merged.

**Comment by krmahadevan** [comment]
@sbaranov-parasoft - Thanks for taking the time to raise this PR. This is now merged.

**Comment by sbaranov-parasoft** [comment]
Thank you all for your reviews.

**Pull request merged**
