### PR TITLE
Fix issue #419: parallel mode was ignored with command line

### PR DESCRIPTION
**Pull request by juherr**

### CODE REVIEW

**Comment by aTan-aka-Xellos** [comment]
Hello.
I tried 6.9.11-SNAPSHOT version withnext maven parameters:
                    <threadCount>3</threadCount>
                    <parallel>tests</parallel>
or with:
                     <property>
                            <name>threadCount</name>
                            <value>13</value>
                        </property>
                     <property>
                            <name>parallel</name>
                            <value>tests</value>
                        </property>
But it doesn't work.
parallel is always 'none' and threadCount is always 5.
https://groups.google.com/forum/#!topic/testng-users/kRmLWw6ts0U

What I'm doing wrong? 
Thanks.

**Comment by juherr** [comment]
There is/was some problems with parallel when used with Surefire (have a look on surefire bug tracker).
First, you shoud be sure you use the latest Surefire version.
Then, how do you know that parallel is always 'non'?

BTW, you should try to run your tests without maven too because we are not able to know if the problem is located in TestNG or Surefire. If you think it is a TestNG issue, feel free to open a new issue.

**Comment by aTan-aka-Xellos** [comment]
If I remember correctly issue in surefire was fixed. We use in our project 2.19 version where it should be fixed.

About 'non':
I've printed value from getParallel() method for ITestContext (tried few of them). The same for threadCount - method getThreadCount() from ITestContext. 

Without maven:
If I put parameters for parallel tests directly into xml suite - it works fine. But we need it through maven for setting parameters from CI.

**Comment by juherr** [comment]
Ok. So please, open a new issue

**Pull request merged**
