### PR TITLE
Bumped up dependency versions

### LINKED ISSUE #1740: Upgrade dependencies
For example AssertJ to the 3.x branch https://joel-costigliola.github.io/assertj/assertj-core.html

### PR DESCRIPTION
**Pull request by atulagrawal**
Fixes #1740

Closes #1740

### Did you remember to?

- [] Add test case(s)
- [x] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Review by juherr — COMMENTED** [review]
Could you check the other dependencies too?

**Comment by atulagrawal** [comment]
I have done the analysis for the dependencies listed under dependencies block:

1. com.google.code.findbugs:jsr305:3.0.1 supports java 8. Ref- http://findbugs.sourceforge.net/
2. org.apache-extras.beanshell:bsh:2.0b6 is latest. Ref https://github.com/beanshell/beanshell/releases
3. com.beust:jcommander:1.72 is latest. Ref - https://mvnrepository.com/artifact/com.beust/jcommander
4. org.apache.ant:ant:1.9.7 is not latest and doesn't support java 8 fully. This needs to be upgraded to org.apache.ant:ant:1.10.3 Ref- http://ant.apache.org/
5. junit:junit:4.12 is latest. Ref - https://mvnrepository.com/artifact/junit/junit
6. org.yaml:snakeyaml:1.17 is not latest and this requires changes in dependency artifact name itself (new artifact - https://bitbucket.org/asomov/snakeyaml-engine)
7. com.google.inject:guice:4.1.0:no_aop is not latest but has java 8 support. Ref - https://github.com/google/guice/wiki/Guice40
8. org.mockito:mockito-core:2.12.0 - is not latest but has java 8 support. Ref - 'org.mockito:mockito-core:2.12.0
9. org.jboss.shrinkwrap:shrinkwrap-api:1.2.6 is latest. Ref - https://mvnrepository.com/artifact/org.jboss.shrinkwrap/shrinkwrap-api
10. org.jboss.shrinkwrap:shrinkwrap-impl-base:1.2.6 is latest - https://mvnrepository.com/artifact/org.jboss.shrinkwrap/shrinkwrap-impl-base
Only following two groovy related dependencies are left are analysis:
testCompile 'org.codehaus.groovy:groovy-all:2.4.7'
testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'

**Comment by juherr** [comment]
snakeyaml still the same group/artifactId -> https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.yaml%22%20AND%20a%3A%22snakeyaml%22

IMO, you can use the latest for other dependencies

**Comment by atulagrawal** [comment]
I have bumped up the dependency version of three artifacts. These artifacts had to be changed for java 8 support. Other dependencies already supports java 8 and i have left the version for them as-is for now. 
Can you please review the PR and help with merge. Thanks.

**Comment by krmahadevan** [comment]
@atulagrawal - Since this basically fixes a bug, it would be good if you could please help update `CHANGES.txt` and add your name to it, so that you get credit for your contribution?

**Comment by atulagrawal** [comment]
@krmahadevan Thanks for highlighting the user email. I totally forgot about it :) I have updated the CHANGES.txt now.

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
ping @juherr.Any additional observations before we request @cbeust for a merge on this ?

**Review by juherr — APPROVED** [review]
Ping @cbeust

**Pull request merged**
