### PR TITLE
Shared Threadpool for normal/datadriven tests.

### LINKED ISSUE #2019: Total thread count in testng parallel tests with dataproviders
### TestNG Version
7.0.0-beta3

### Expected behavior
Need to have Global thread count so that we can control total thread when we have x number of thread-count and x number of data provider thread count.

### Actual behavior
Let say,If we have 10 thread count and 10 data provider thread count then we will end up running 100 thread.  

I am not reporting this is as a bug. Created this issue so that it will kick off the discussion around this and if it can be considered as a feature request.
https://groups.google.com/forum/#!topic/testng-users/BKfSgHoAChU

### Is the issue reproducible on runner?
Yes

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2019

Fixes #2019  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`
- [X] Auto applied styling via `./gradlew autostyleApply`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

**Note:** For more information on contribution guidelines  please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### CODE REVIEW

**Review by juherr — COMMENTED** [review]
Except the dtd modification, the rest looks great.

I propose you moving and tracking all the dtd changes and related code in a dedicated pull request that we will merge once in a new dtd version (maybe even better to move to xsd). Wdyt?

**Comment by krmahadevan** [comment]
Sure. I remember the list of additions to the DTD that I made. 

Now regarding the xsd, since i dont know a lot about it i had some questions 

1. Would that be embedded in the jar or again hosted online?
2. If it would be hosted online how do we version control that as well without needing the users to update their suite files?

Now regarding this PR can we merge it? I was thinking of going for a release with this changeset.

**Comment by juherr** [comment]
Please exclude the dtd modification from this PR and move it to the dedicated one.

XSD is another subject we can tackle later.

**Comment by krmahadevan** [comment]
@juherr 

> Please exclude the dtd modification from this PR and move it to the dedicated one.

* U want the DTD modification to be done on the same file but in a separate PR (or)
* U want the DTD modification to be created in a totally different dtd file ( For e.g., [this file](https://github.com/testng-team/testng/blob/master/testng-core/src/main/resources/testng-1.1.dtd) ) ?

**Comment by juherr** [comment]
I want to merge this pr without xml potential  regression or issue.

And I want to manage schema evolutions once in its own pr. With this strategy it will help to merge your previous pr too.

**Comment by krmahadevan** [comment]
> I want to merge this pr without xml potential regression or issue.
> 
> And I want to manage schema evolutions once in its own pr. With this strategy it will help to merge your previous pr too.

I dont think there's going to be any regression because the DTD got updated. I havent heard of anyone relying on the DTD for some sort of code generation etc., in all these years.

Can we merge this PR as is and I will raise a new PR wherein I will remove the DTD additions from 1.0 dtd and add them to the 1.1 dtd (If this DTD getting updated is such a big concern).

**Comment by krmahadevan** [comment]
and oh btw, since u had approved the earlier PR, its already merged into `master`

**Comment by krmahadevan** [comment]
@juherr - Please review this PR again. I have reverted the changes done to 1.0-dtd file and added those changes to 1.1-dtd (I did this by copying the contents of 1.0-dtd to 1.1-dtd and then moving the new changes into it).

**Review by juherr — APPROVED** [review]

**Pull request merged**
