### PR TITLE
Fixing a hard dependency on Guice Libraries

### LINKED ISSUE #2223: testng 7.1.0 java.lang.ClassNotFoundException: com.google.inject.Stage
### TestNG Version
TestNG 7.1.0

### Actual behavior

the testng-remote integration test failed
https://travis-ci.org/testng-team/testng-remote/jobs/481901771

```
[RemoteTestNG] revisions:
	git.commit.id=32c8977
	git.branch=32c8977911e409c8c8c2d4bce973e94d2acf5ca7
	git.build.version=1.4.1-SNAPSHOT
[RemoteTestNG] loaded class org.testng.internal.Version at file:/home/travis/.groovy/grapes/org.testng/testng/jars/testng-7.1.0.jar
[RemoteTestNG] detected TestNG version 7.1.0
Caught: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
	at org.testng.remote.RemoteTestNG$main.call(Unknown Source)
	at TestNGTest.run(TestNGTest.groovy:49)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	... 9 more
[BaseMessageSender] Stopped receiver
```

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

https://github.com/testng-team/testng-remote/blob/master/remote-test/src/test/groovy/Tester.groovy

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2223

Fixes #2223  .

### Did you remember to?

- [ ] Add test case(s)
- [X] Update `CHANGES.txt`

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - I have tested this locally by installing the changes locally, adding up the newly published version as a maven dependency and then running a test.

```
22:05 $ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.rationaleemotions:issue_2223 >------------------
[INFO] Building issue_2223 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ issue_2223 ---
[INFO] com.rationaleemotions:issue_2223:jar:1.0-SNAPSHOT
[INFO] \- org.testng:testng:jar:7.1.1-SNAPSHOT:test
[INFO]    +- com.beust:jcommander:jar:1.72:test
[INFO]    +- org.apache.ant:ant:jar:1.10.3:test
[INFO]    |  \- org.apache.ant:ant-launcher:jar:1.10.3:test
[INFO]    +- junit:junit:jar:4.12:test
[INFO]    |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]    \- org.yaml:snakeyaml:jar:1.21:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.202 s
[INFO] Finished at: 2020-03-09T22:05:51+05:30
[INFO] ------------------------------------------------------------------------
```

```
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ issue_2223 ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.rationaleemotions.SampleTest
Hello world
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.387 s - in com.rationaleemotions.SampleTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.056 s
[INFO] Finished at: 2020-03-09T22:06:06+05:30
[INFO] ------------------------------------------------------------------------
```

ping @missedone - Can you please check if this fixes the problem from TestNG eclipse plugin perspective as well ?

**Review by juherr — APPROVED** [review]
I don't understand why it is fixing the issue but LGTM if @missedone confirms the fix.

**Comment by krmahadevan** [comment]
Based on an email confirmation from @missedone I merged this changes.

**Comment by nmohtashim** [comment]
I am also facing this 
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more


can any one help me with this

**Pull request merged**
