### PR TITLE
TestNG doesn't use the searchable loaders for JUnit tests

### PR DESCRIPTION
**Pull request by iignatev**
working on [CODETOOLS-7901875]( https://bugs.openjdk.java.net/browse/CODETOOLS-7901875), I noticed that TestNG doesn't use classloaders added by TestNG::addClassLoader to load JUnit test classes and always uses the current classloader to load them. This makes usage of TestNG in jtreg test harness a bit cumbersome.

here is the excerpt from jtreg bug w/ more details:
-- JUnit uses o.j.runner.Description as a description for a test or test suite, this class doesn’t store a reference to a test class, but has getTestClass method to return it. getTestClass assumes that the test class is accessible for JUnit’s classloader 
 -- if Description::getTestClass does not found a class, it returns null 
 -- from what I see, there is no code in JUnit which depends result of on Description::getTestClass 
 -- the guy who creates Description has a reference to the test class, so it’s possible to pass that reference to Description and it looks like it’s fixed in new version of junit[1] 
 - for all o.j.r.notification.RunNotifier method which gets o.j.runner.Description instance, o.t.j.JUnit4TestRunner$RL uses it to create o.testng.ITestResult in createTestResult method and then passes ITestResult to actual listeners 
 -- o.t.j.JUnit4TestRunner$RL::createTestResult creates o.t.junit.JUnit4TestClass and JUnit4TestMethod instances using o.j.runner.Description 
 -- c-tor of both classes assume that o.j.runner.Description::getTestClass returns a reference, if it returns null, NPE will be thrown 
 -- TestNG has an aux class to deal w/ classloaders related problems — o.t.internal.ClassHelper, but o.t.junit.JUnit4TestClass / JUnit4TestMethod don't use it
 - when we run tests in agentvm mode, TestNG/JUnit and the runner(c.s.j.regtest.agent.TestNGRunner) are available for Application classloader and loaded by it, but tests are loaded by a classloader created in c.s.j.regtest.agent.MainActionHelper::runClass. thus test classes are unavailable for TestNG/JUnit classes, we get NPE at the very first invocation of o.t.j.JUnit4TestRunner$RL

### CODE REVIEW

**Comment by krmahadevan** [comment]
@iignatev - Thanks for the PR. Can you please help add an entry into `CHANGES.txt`? Also would it be possible for you to please help add a unit test that vets out the change ? That way we can ensure that there are no further regressions due to some changes in TestNG.

**Comment by iignatev** [comment]
@krmahadevan, testing the fix I failed to reproduce the original issue. it appears that since the time I bumped into this issue you have switched to junit4.12 which kinda workarounds this problem on their side. Nevertheless, the fix makes sense regardless of the version of junit and it'd be better to have it integrated and so testng won't depend on how junit implements `org.junit.runner.Description`

**Review by juherr — APPROVED** [review]
Thanks for the fix!

LGTM 👍 
Ping @cbeust

**Comment by krmahadevan** [comment]
@juherr - Based on the email that @cbeust sent, I am going ahead and getting this merged. I hope that is fine.

**Pull request merged**
