### PR TITLE
#2974: Add overrideGroupsFromCliInParentChildXml test

### LINKED ISSUE #2974: Regression in -groups CLA
### TestNG Version
7.8.0

### Expected behavior
-groups runner parameter allows to override all groups defined in a suite xml file

### Actual behavior
-groups runner parameter is ignored

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
1. There is parent xml suite which defines groups.run.include "abc" and includes child xml suite
2. There is child xml suite which includes a test class
3. There is a test class which has two tests: one has "abc" group and other has "xyz" group
4. Start test run with -groups xyz

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

### PR DESCRIPTION
**Pull request by dr29bart**
#2974: Add a test method for "Regression in -groups CLA"

Closes #2974

### CODE REVIEW

**Comment by krmahadevan** [comment]
@dr29bart - are you also planning to add changes to fix this issue? I ask because if this PR is containing a test that will reproduce the problem then it cannot be merged since it sill start breaking the build.

**Comment by dr29bart** [comment]
@krmahadevan unfortunately, I don't have a solution. The PR is a just sample of test case for the bug. 
I am ok closing this PR without merging it.

**Comment by juherr** [comment]
@dr29bart The fix should be easy. Do you want to try a fix?

You think it is a regression. Could you tell us when the behavior changed?
The documentation is not precise enough about the expected behavior: addition instead of overriding could be a valid behavior too. In such cases, we prefer to choose the historical behavior.
The fix should include a documentation update too.

**Comment by dr29bart** [comment]
The 'groups' parameter overrides any defined groups in parent and child xml files in 7.3.0
Starting with 7.4.0 the parameter does not affect scope defined in xml files. 

@juherr the behavior has changed in 7.4.0 with this commit:
https://github.com/testng-team/testng/commit/9c6cb875005429cb5a9b66b49160f3e0ac91dc0e#diff-c9ad087b236ef4e9750660f8daa935b53c2356a437d3bf5d069ba370e8994cf6R499
It initializes m_currentRun 
```
m_currentRun = new XmlRun();
```
which then affects condition in XmlSuite#getIncludedGroups:
```
    if (m_xmlGroups != null && (m_xmlGroups.getRun() != null)) {
      return m_xmlGroups.getRun().getIncludes();
    }
```

There is **XmlTest**#setIncludedGroups which works with xmlGroups,I tried to use the same approach for **XmlSuite**#setIncludedGroups. Please let me know if there is a better way to address the issue.

**Review by juherr — APPROVED** [review]

**Review by krmahadevan — APPROVED** [review]

**Pull request merged**
