### PR TITLE
Fix maven tests: Set resources location

### PR DESCRIPTION
**Pull request by juherr**
Fix tests with maven.

Reported by @VladRassokhin on #846.

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Yep, [all 553 tests are green](https://teamcity.jetbrains.com/viewLog.html?buildId=615038&tab=buildResultsDiv&buildTypeId=bt416&guest=1)

**Comment by VladRassokhin** [comment]
BTW, If you are interested, I could give you access to 'TestNG' project on our public TeamCity server, so you could edit it settings. Anyway it have configurations to build and run tests for TestNG using maven and ant (looks like there no more ant builds, will replace with gradle one) and more important - inspections and duplicates reports.

**Comment by juherr** [comment]
@VladRassokhin I've just created an account -> juherr

**Comment by cbeust** [comment]
@juherr I was going to point out that this missing property was probably the reason why tests were failing on Maven but you beat me to it. Thanks!

**Comment by juherr** [comment]
@VladRassokhin I played a bit with TeamCity but I didn't find how to specify minimum java version on build.

**Comment by VladRassokhin** [comment]
@juherr If you're talking about kobaltw problem - that's because JAVA_HOME on agent points to Java 1.6. That could be solved by settings env.JAVA_HOME=env.JDK_18 as build configuration parameter.
Unfortunately there no way to set parameter like "Any Java newer that 1.X". 
Also there is problem in kobalt, since it not check java version prior to execute java code.

**Pull request merged**
