### PR TITLE
Wrong text for assertEquals

### LINKED ISSUE #1935: Wrong text for assertEquals
latest

### Expected behavior
When an assertEquals fails, it should say "Did expect [X] but found [Y]".
This is logically correct English and understandable.

### Actual behavior
When a simple Assert.assertEquals("x", "y") is executed, it fails saying:

"Did not expect to find [y] but found [x]"

The "NOT" is completely wrong. It did NOT expect to find y, but it did find x?  What's wrong then? it should state what it expected and what it found instead!

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

assertEquals("y", "x")

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1935

Fixes #1935  #1921 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Review by juherr — APPROVED** [review]

**Comment by krmahadevan** [comment]
Merged this changes since @juherr has helped approve the changes

**Comment by HelgeStenstrom** [comment]
When can we expect this to be fixed in a release? Version 7.0.0-beta3 seems to have the problem.

**Comment by juherr** [comment]
@HelgeStenstrom It should be fixed since 7.0.0-beta2
Could you open a new issue with a sample?

**Comment by HelgeStenstrom** [comment]
My pom.xml:


```xml
        <!-- https://mvnrepository.com/artifact/org.testng/testng -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.0.0-beta3</version>
            <scope>test</scope>
        </dependency>
```


My test file:

```java
import org.testng.annotations.Test;

import static org.testng.Assert.assertTrue;

public class testTestNg {
    @Test
    public void showFail() {
        assertTrue(false, "MyMessage");
    }

    @Test(expectedExceptions = AssertionError.class, expectedExceptionsMessageRegExp = "MyMessage did not expect to find \\[true\\] but found \\[false\\]")
    public void version7Behavior() {
        assertTrue(false, "MyMessage");
    }

    @Test(expectedExceptions = AssertionError.class, expectedExceptionsMessageRegExp = "MyMessage expected \\[true\\] but found \\[false\\]")
    public void version6Behavior() {
        assertTrue(false, "MyMessage");
    }
}
```


I the test "showFail", I get:
`java.lang.AssertionError: MyMessage did not expect to find [true] but found [false]`

which is bad language. Isn't that exactly what this issue is about?

**Pull request merged**
