### PR TITLE
Add Java9 in Travis build

### PR DESCRIPTION
**Pull request by juherr**
You can see the effect on my travis: https://travis-ci.org/juherr/testng/builds/194972707

Without surprise, it is not working well on Java9 for the moment.

### CODE REVIEW

**Comment by cbeust** [comment]
Indeed, although the current breakage seems to be coming from Gradle?

**Comment by juherr** [comment]
Yes, I'm trying to upgrade it to see if the issue will be fixed alone.

**Comment by juherr** [comment]
For reference: https://github.com/gradle/gradle/issues/1095

**Comment by cbeust** [comment]
I need to try this with Kobalt too :)

**Comment by juherr** [comment]
Yes, good luck! Fyi, I failed to fix the issue :( https://github.com/juherr/testng/commits/java9-test
We will have to wait&see.

**Pull request merged**
