### PR TITLE
Remove useless retention of parameters

### PR DESCRIPTION
**Pull request by juherr**
Quick try for #1173
The merge will allow @ben-manes to be able to test the fix easily.

### CODE REVIEW

**Comment by ben-manes** [comment]
I'll try building the jar and have Gradle reference a local jar. Give me a few minutes, just finishing lunch :)

**Comment by cbeust** [comment]
Looks like I don't need to merge this for @ben-manes to test. Ben I'll wait to hear back from you whether this works.

**Comment by juherr** [comment]
Yep :) 

But I think the change is still relevant because it removes useless code. ;)

**Comment by cbeust** [comment]
Alright then, merged!

**Pull request merged**
