### PR TITLE
UI_REVAMP FEATURE

### PR DESCRIPTION
**Pull request by GullapalliAkhil**
This commit has all the changes required to implement the UI-REVAMP Feature.
Raising the Pull request which is alternate to ''''UI Revamp for the HTML Report feature to make the report more readable. #2201'''.
Screenshot 2020-02-13 at 3 36 16 AM
Screenshot 2020-02-13 at 3 36 05 AM

### CODE REVIEW

**Comment by GullapalliAkhil** [comment]
@krmahadevan, I created a pull request which has commits similar to pull request 'UI Revamp for the HTML Report feature to make the report more readable. #2201', so please close the #2201 and review this.
This branch has no conflicts with the base branch.
And sorry for messing the things with #2201, as I am a nubie to this.

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
@cbeust  @juherr - Can we go ahead and have this merged ?

**Review by juherr — APPROVED** [review]

**Comment by krmahadevan** [comment]
@juherr @cbeust - Can we merge this PR ?

**Comment by cbeust** [comment]
LGTM.

**Pull request merged**
