### PR TITLE
Parallelization refactor

### PR DESCRIPTION
**Pull request by selenareneephillips**
Reverted to System.out.print for logging until we come up with a better solution for debugging failures on the CI builds.

Relaxed the parallelization verification.

Removed unused methods as a result of refactoring.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@selenareneephillips 

> Reverted to System.out.print for logging until we come up with a better solution for debugging failures on the CI builds.

We have taken care of this. For any build that fails, in the Travis console you should be seeing something like this 

```
Publishing build scan...
https://gradle.com/s/k77pjuulupe6m
```

You can get the details of the tests, if you open up the specific URL.

**Comment by juherr** [comment]
@krmahadevan build scan allows us to show which tests are failing but it doesn't allow to debug it. Sadly, parallel tests only fail on travis :/

**Comment by selenareneephillips** [comment]
@juherr @krmahadevan Pinging.

**Comment by krmahadevan** [comment]
@selenareneephillips - I don't have any specific comments from my side. 
@juherr / @cbeust - Please help get this changes merged if you are fine with it as well.

**Review by juherr — APPROVED** [review]

**Pull request merged**
