### PR TITLE
#2734 keep the initial order of listeners

### LINKED ISSUE #2734: Class Level Test Annotation does not allow the setting of priorrities for the methods
### TestNG Version
7.5

### Expected behavior
We should be able to set the priority of a test method even if the Test annotation is on the class.

### Actual behavior
The piorities we set are ignored

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
In my example I have a test case that ha different results based on the order. I will ry and change the order so that **testBBB** is executed first. I use the listener to make sure that the priority for the other method is higher.

### Test Sample
(Edited from the original ass I had used a wrong example):

```java
@Test
public class TestsPriority2 {
    
    public static int value = 100;
    
    
    public void testAAA() {
        value-=20;
    }
    
    
    public void testBBB() {
        value*=2;
    }
    

}

```

### Test

```java
@Test
    public void testNormalTestMethod_ChangedPriority_classLevelTest() {
        TestsPriority2.value=100;

       
        // Rampup
        TestNG myTestNG = createTestNG();
        TestListenerAdapter tla = fetchTestResultsHandler(myTestNG);

        // Define suites
        XmlSuite mySuite = addSuitToTestNGTest(myTestNG, "Automated Suite External priority Checks Testing");

        // Add listeners
        mySuite.addListener(PriorityThing.class.getTypeName());

        // Create an instance of XmlTest and assign a name for it.
        XmlTest myTest = attachTestToSuite(mySuite, "Test Simple External priority Checks Tests");
       

        //Define packages
        final Class<TestsPriority2> l_testClass = TestsPriority2.class;
        myTest.setXmlClasses(Collections.singletonList(new XmlClass(l_testClass)));

        myTestNG.run();

        assertThat("We should have no failed methods", tla.getFailedTests().size(), is(equalTo(0)));

        assertThat("We should have no failed methods", tla.getPassedTests().size(), is(equalTo(2)));
       assertThat("One of the results should be of prriority 2", tla.getPassedTests().stream().anyMatch(t -> t.getMethod().getPriority()==2));
        
        
        assertThat("We should not have the values in alfabetical order", TestsPriority2.value, equalTo(180));
     
    }
```

### Listener

```java
public class PriorityThing implements IAnnotationTransformer , ITestListener{
    protected static Logger log = LogManager.getLogger();
    
    @Override
    public void onTestStart(ITestResult result) {
        log.info("testStart: method : {} : priority is {}", result.getName(), result.getMethod().getPriority());
    }

    protected static Logger log = LogManager.getLogger();
    
    @Override
    public void onStart(ITestContext context) {
        for (ITestNGMethod lt_testNGMethod : context.getSuite().getAllMethods()) {

            log.info("onStart : Method {} priority is {}",lt_testNGMethod.getMethodName(),lt_testNGMethod.getPriority());
        }
        
    }

    @Override
    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor,
            Method testMethod) {
        
        
        if (testMethod != null && testMethod.getName().equals("testAAA")) {
            annotation.setPriority(2);
            log.info("transform : Changing priority. priority for {} is {}",testMethod.getName(),annotation.getPriority());
            
        }
    }

}
```

### PR DESCRIPTION
**Pull request by asolntsev**
We need to run listeners at the same order in which they were declared in @Listeners({First.class, Second.class, Third.class})

Fixes #2734 and #1219

### Did you remember to?

- [ ] Add test case(s)
- [x] Update `CHANGES.txt`
- [x] Auto applied styling via `./gradlew autostyleApply`

### CODE REVIEW

**Comment by krmahadevan** [comment]
@asolntsev - Thank you so much for taking the time to raise a PR. Can you please help add tests that will essentially vet out the changes for the defects that you linked?

**Comment by asolntsev** [comment]
@krmahadevan Ugh... It was not easy, but I added the test: TestRunnerTest.java

**Review by juherr — APPROVED** [review]

**Comment by krmahadevan** [comment]
@asolntsev - There are test failures. Please help take a look and help fix them.

**Comment by asolntsev** [comment]
@krmahadevan I have fixed the tests. 

I think the last CI failure is not caused by my changes. It seems to be some flaky test caused by concurrent tests run:

```
test.failedreporter.FailedReporterTest > tearDown failure marker
  Error:   0.0sec test.failedreporter.FailedReporterTest > tearDown
  java.nio.file.FileSystemException: C:\Users\RUNNER~1\AppData\Local\Temp\testng-tmp-2956855115414577614673\testng-failed.xml: The process cannot access the file because it is being used by another process.
```

**Review by krmahadevan — APPROVED** [review]

**Comment by krmahadevan** [comment]
@asolntsev - Thank you so much for helping out with this PR. This now stands merged. Look forward to more such contributions

**Comment by asolntsev** [comment]
Yes! Achievement unlocked :)

**Pull request merged**
