### PR TITLE
WIP: Issue #128

### LINKED ISSUE #128: Using Object[] and Method as parameters for a test in a certain order yields an IllegalArgumentException, citing a type mismatch.
BUILD: Eclipse plugin 6.3.0.20111017_2337

DESCRIPTION:
Two data providers that provide two parameters are defined. The first data provider provides a java.lang.reflect.Method as the first parameter and an Object array as the second. The second data provider reverses the order of the parameters.

One empty test is defined to use the first data provider. Another empty test is defined to use the second data provider.

Run this test.

The data providers and tests are defined below:

```
@DataProvider(name = "methods")
public Object[][] getMethods() throws NoSuchMethodException
{
    return new Object[][]{
            new Object[]{String.class.getMethod("toString"), new Object[0]},
    };
}

@Test(dataProvider = "methods")
public void testInvokeRemote(Method param1, Object[] param2) throws Exception
{
    // This fails with: java.lang.IllegalArgumentException: argument type mismatch
}

@DataProvider(name = "methods2")
public Object[][] getMethods2() throws NoSuchMethodException
{
    return new Object[][]{
            new Object[]{new Object[0], String.class.getMethod("toString")},
    };
}

@Test(dataProvider = "methods2")
public void testInvokeRemoteReversed(Object[] param1, Method param2) throws Exception
{
    // This works.
}
```

EXPECTED RESPONSE:
The order of parameters that a test method accepts are irrelevant to the results of that test.

OBSERVED RESPONSE:
The first test (with parameter types Method, Object[]) fails with an IllegalArgumentException, citing a type mismatch.

The second test (with the same parameter types in reverse order) passes without incident.

REPRO RATE: 10/10

### PR DESCRIPTION
**Pull request by juherr**
### DO NOT MERGE

Fixes #128.

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

I'm not able to finish it quickly. If someone wants to continue it from my branch.
I'm free to discuss the issue and its resolution.

Ping @krmahadevan Do you?

### CODE REVIEW

**Comment by juherr** [comment]
The fix may not be easy because of the logic duplication... Will see.

**Comment by juherr** [comment]
@cbeust The current draft of the fix is enforcing the full mapping between test method and its data provider. Agree with that?

**Comment by krmahadevan** [comment]
@juherr - I am ready to give this a try. Can you please fill me in on the details ?

**Comment by juherr** [comment]
@krmahadevan I don't know if we are looking to change the behavior but the rule is not really documented and I think the rule will be easier to understand. Maybe a configurable behavior (warning or exception) could a good idea in a first step.

BTW, the issue is easy to reproduce with a breakpoint in ReflectionRecipes.
In case of native TestNG injection, the appropriate object will be provided by both `ReflectionRecipes#inject` and  `Parameters#getInjectedParameter`.

So, in the case of `[Method, ?]` params, we will try to call the `[Method, Method]` method which doesn't exist (or worst, exists) and `?` will be ignored.

IMO, `Parameters#getInjectedParameter` should be removed but configuration methods are not using `ReflectionRecipes` (for the moment?) and native injection will be broken with a simple removal. :(
An another option, or maybe an additional one, could be to skip params (with an appropriate log) which are not matching the one we are currently looking for (but we need to find the samples with a good coverage of the feature).

Let me know if you need more details and thank for the help :)

**Comment by krmahadevan** [comment]
@juherr - Thanks for providing those insights.. I am working on figuring this out and on this.

**Comment by krmahadevan** [comment]
@juherr - Just thinking out loud...

The current edit check that you add [here](https://github.com/juherr/testng/blob/2badf2f4d9e74eb4587bb3e309fba1a5f3149394/src/main/java/org/testng/internal/reflect/ReflectionRecipes.java#L374-L378) if controlled by a JVM argument wherein 

* if JVM argument is `false` or `not present`, the message of the exception gets logged on the console.
* If JVM argument is `true` or `present`, then the exception that you have added would be raised.

should basically wrap this up. What do you think ? 

The message could however use some pretty printing. Currently it shows up something like this

```
testInvokeRemote don't bind all parameters provided by the data provider. You have to add parameter(s) for [[Ljava.lang.Object;@6438a396]
```

Maybe we could apply some `Arrays.toString()` invocations or something like that, to make it look better.

**Comment by juherr** [comment]
@krmahadevan 
+1 for jvm arg (but it should be `present` **AND** `true` for the exception)
+1 for the message improvement

**Comment by krmahadevan** [comment]
@juherr  I have raised a new PR https://github.com/cbeust/testng/pull/1459 Please help take a look

**Pull request merged**
