### PR TITLE
Rename doc folder to docs

### PR DESCRIPTION
**Pull request by juherr**
Because GitHub is now supporting a folder for the doc (but must be named `docs`).

### CODE REVIEW

**Comment by juherr** [comment]
@cbeust could you configure the repository to use the folder now? 

http://cbeust.github.io/testng is supposed to work after that.

**Comment by cbeust** [comment]
Sure, how? :)

**Comment by juherr** [comment]
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by cbeust** [comment]
Done: http://cbeust.github.io/testng/

**Comment by juherr** [comment]
Great ! Next steps : check pages and links,  backport changes from testng-team/testng-site and make the switch (one more time)

**Pull request merged**
