### PR TITLE
Avoid Compilation errors on Semeru JDK flavour.

### PR DESCRIPTION
**Pull request by krmahadevan**

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - Now I saw a different error again on the same osgi dependencies (with not being able to resolve artifacts). I have pushed an additional commit here that bumps up the test versions (Hope that would fix it)

https://github.com/krmahadevan/testng/actions/runs/3467189157/jobs/5791820079

**JDK 11 Zulu**

```
FAILURE  11.5sec, org.testng.test.osgi.PlainOsgiTest > versionShouldStartWithDigit
    shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.apache.geronimo.specs:geronimo-atinject_1.0_spec:jar:1.0
```

https://github.com/cbeust/testng/actions/runs/3467191687/jobs/5791824963

**JDK17 SapMachine**

```
Error:   6.1sec org.testng.test.osgi.PlainOsgiTest > versionShouldStartWithDigit
  shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.ops4j.pax.swissbox:pax-swissbox-core:jar:1.8.2
```

**Comment by vlsi** [comment]
Is it reproducible?
Frankly speaking, I've been facing connectivity issues between GitHub Actions and repo1.maven.org in pgjdbc.

See https://github.com/pgjdbc/pgjdbc/actions/runs/3459838388/jobs/5775689519#step:8:539

```
                        Caused by: shaded.org.apache.http.conn.ConnectTimeoutException: Connect to repo1.maven.org:443 [repo1.maven.org/146.75.28.209] failed: connect timed out
                            at app//shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
                            at app//shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
                            at app//shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
                            at app//shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
                            at app//shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
                            at app//shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
                            at app//shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
                            at app//shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
                            at app//shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
                            at app//org.ops4j.pax.url.mvn.internal.wagon.ConfigurableHttpWagon.execute(ConfigurableHttpWagon.java:162)
                            at app//shaded.org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1095)
                            ... 42 more
                            Caused by: java.net.SocketTimeoutException: connect timed out
                                at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
                                at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
                                at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
                                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                                at java.base/java.net.Socket.connect(Socket.java:609)
                                at shaded.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
                                at shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
                                ... 52 more
                Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.osgi:org.osgi.service.jdbc:jar:1.0.0
                    at app//shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
                    at app//shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
                    at app//shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
                    at app//shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
                    at app//org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
                    ... 24 more
```

As it did not fail much, I have not explored if there's a way to configure retries or something like that.

**Comment by vlsi** [comment]
The artifact you mention is listed on Central, so the version should not be an issue: https://repo1.maven.org/maven2/org/apache/geronimo/specs/geronimo-atinject_1.0_spec/1.0/

**Comment by krmahadevan** [comment]
@vlsi - It happens almost for every build and every time its a different artifact and confined to only one of these https://github.com/cbeust/testng/blob/a678d0586e2cf2ccf39d8997a24517c25f7be366/testng-test-osgi/testng-test-osgi-build.gradle.kts#L28-L31 and its not across all JDK flavours. Its random. I am not able to see/determine a pattern on when this happens

**Comment by vlsi** [comment]
I think ArtifactResolutionException is not related to Gradle build script.
The error comes from shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver which is osgi container trying to resolve the dependency.

**Comment by krmahadevan** [comment]
@vlsi - Any suggestions on how to get this sorted out ?

**Review by juherr — APPROVED** [review]

**Pull request merged**
