### PR TITLE
Enabling test result logging via gradle for travis debugging.

### LINKED ISSUE #1240: Enrich the test results showing mechanism in Travis CI
### Expected behavior
Currently when there is a failure in the Travis-CI builds, there is not much information available to figure out what test failed, so that it can be easily fixed.

Travis also doesn't seem to have a way in which one can download the gradle test output file from the build system.

### Actual behavior

The build output should basically show the test results in a way such that the user can look at the console logs and understand what test went wrong.
### Is the issue reproductible on runner?

- [X] Shell
- [ ] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

There is no test case specifically needed to recreate the problem. This issue is related to failures in Travis-CI

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes #1240  .

### Did you remember to?

- [ ] Add test case(s)
- [X] Update `CHANGES.txt`

### CODE REVIEW

**Comment by krmahadevan** [comment]
@juherr - Please see if this can be merged so that we start getting visibility into what is passing and what is failing.

**Comment by krmahadevan** [comment]
I wasn't able to see the sort of output that I was seeing on my local machine when i was running `./build-with-gradle`.

**Comment by juherr** [comment]
What is the expected output with this change?

**Comment by krmahadevan** [comment]
I was hoping to see a running commentary of what passed/failed on the console when the build runs. When I ran the build locally I was able to see it but not able to see the same output when Travis runs builds. 

The intention was to help make it easy to debug failures when Travis builds pull requests. Currently it's a bit difficult to figure out what failed in a build ( inaccessibility of the test reports makes the debugging process even more cumbersome).

**Comment by juherr** [comment]
Have a look on https://github.com/anshooarora/extentx/issues/70

**Comment by krmahadevan** [comment]
Thanks. In the meantime do you think that we could use a Tests specific debug listener that uses `IInvokedMethodListener` and simply logs data to console ?

**Comment by juherr** [comment]
Yes, it could be an option too.

**Comment by krmahadevan** [comment]
Thanks Julien. I will give it a try and see how it goes. 

In the meantime I stumbled into this blog which talks about uploading stuff to `gh-pages`. Maybe we can consider that as well. 

http://sleepycoders.blogspot.in/2013/03/sharing-travis-ci-generated-files.html?m=1

**Comment by juherr** [comment]
Not a huge fan to push to gh-pages. I suppose it will be heavier to clone the repo after.

**Comment by krmahadevan** [comment]
We could push to a different repository within the testng-team org also. It neednt be to the same repository. 

We just need a way to view the test results to help in debugging.

**Comment by krmahadevan** [comment]
@juherr - I have tried everything possible, but for some reason the JDK7 builds crash within a minute itself. Not sure what exactly is going on with Travis. Here's the latest Travis CI link https://travis-ci.org/cbeust/testng/builds/175935757

w.r.t the changes in this PR, I have tried to build a console reporter which reports only failures. The output would look something like below

```
Gradle Test Executor 2 STANDARD_OUT
    Failures in <suite> :TestNG, <test> :removeThis
    test.DontCheckInThisClass.anotherTestMethod()
    StackTrace:
     java.lang.RuntimeException: simulating a failure
        at test.DontCheckInThisClass.anotherTestMethod(DontCheckInThisClass.java:17)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:129)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:88)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:120)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    ... Removed 30 stack frames

    test.DontCheckInThisClass.testMethod()
    StackTrace:
     java.lang.AssertionError: expected [false] but found [true]
        at test.DontCheckInThisClass.testMethod(DontCheckInThisClass.java:12)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:129)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:88)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:120)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    ... Removed 36 stack frames

```

Please let me know if you are fine with getting this merged.

**Comment by juherr** [comment]
What is `test.DontCheckInThisClass`?

> We could push to a different repository within the testng-team org also. It neednt be to the same repository.

True, good idea! Repo created: https://github.com/testng-team/testng-travis-reports/

**Comment by krmahadevan** [comment]
> What is test.DontCheckInThisClass?

That was just a dummy class that I added locally to simulate a failure. I named the class `DontCheckInThisClass` so that I don't end up pushing in this sample class into the codebase.

> True, good idea! Repo created: https://github.com/testng-team/testng-travis-reports/

Thanks. Can you also please help create the gh-pages branch ( http://blog.teamtreehouse.com/using-github-pages-to-host-your-website ) so that I can try and experiment to see how I can make the test reports available by following the blog (http://sleepycoders.blogspot.in/2013/03/sharing-travis-ci-generated-files.html )?

**Comment by juherr** [comment]
You have write rights on the repo. You should be able to do it yourself.
Let me know if it is not working or if you need help.

**Comment by krmahadevan** [comment]
@juherr - I will figure out the part of uploading the test results to our new github test results repository. In the meanwhile this PR should address the immediate need of having a way to look at the logs.

Please see here https://travis-ci.org/cbeust/testng/jobs/176253915 
I have added a running commentary kind of mechanism that prints the test results as and when tests run to completion.

If there are any failures they would reported at the end of the build (I have added a sample of how it can look like in this comment https://github.com/cbeust/testng/pull/1236#issuecomment-260537460) 

Please let me know if this can be accepted.

**Comment by juherr** [comment]
LGTM 👍 Ping @cbeust 

Maybe only failed tests are useful, and maybe we can sort results by their status.

**Pull request merged**
