### PR TITLE
Improve error message when data provider returns a null value

### LINKED ISSUE #1509: Improve error message when data provider returns a null value
### Expected behavior
The error message should clearly state that the data provider returned a null value.

### Actual behavior
The error message is something like below

```
Data Provider public static java.lang.Object[][] com.rationaleemotions.stackoverflow.qn45790482.MyDataProviderWithITestContextClass.getDataFromDataprovider(org.testng.ITestContext) must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not class [[Ljava.lang.Object;
```

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

```java
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class SampleTestClass {
    @Test(dataProvider = "dp")
    public void demo(int i) {
        System.out.println(i);
    }

    @DataProvider(name="dp")
    public Object[][] getData() {
        return null;
    }

}
```

More details available here : https://stackoverflow.com/a/45799043/679824

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #1509

Fixes #1509  .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @juherr

**Review by juherr — APPROVED** [review]
LGTM :+1:
Ping @cbeust

**Comment by cbeust** [comment]
Can you fix the conflicts in `CHANGES.txt`?

**Comment by krmahadevan** [comment]
@cbeust - I fixed the conflicts and pushed in the changes. Please take a look

**Pull request merged**
