### PR TITLE
Krmahadevan fix 564

### LINKED ISSUE #564: Optional always requires Parameters is this really needed?
I have same @Test methods that implement an interface. I do not want to provide @Parameters to these methods, so I only use @Optional for the method parameters, but this is not allowed.

Example:

```java
    @Test
    public void testWithoutParameter() {
        // OK
    }

    @Test
    public void testWithParameter(String unUsedParameter) {
        // org.testng.TestNGException: 
        // Method testWithParameter requires 1 parameters but 0 
        // were supplied in the @Test annotation.
        //
        // This is a valid error to me.
    }

    @Parameters("unUsedParameter")
    @Test
    public void testWithParameterAndParametersAnnotation(String unUsedParameter) {
        // org.testng.TestNGException: 
        // Parameter 'unUsedParameter' is required by @Test on method 
        // testWithParameterAndParametersAnnotation but has not been 
        // marked @Optional or defined
        // in C:\Users\asdf\AppData\Local\Temp\testng-eclipse--1694500678\testng-customsuite.xml
        // 
        // This is a valid error to me.
    }

    @Parameters("unUsedParameter")
    @Test
    public void testWithParameterAndParametersAnnotationAndOptionalAnnotation(@Optional String unUsedParameter) {
        // OK
    }

    @Test
    public void testWithParameterOnlyOptionalAnnotation(@Optional String unUsedParameter) {
        // org.testng.TestNGException: 
        // Method testWithParameterOnlyOptionalAnnotation 
        // requires 1 parameters but 0 were supplied in the @Test annotation.
        //
        // I would expect this test to succeed, because I 
        // defined the method parameter 'unUsedParameter' as optional.
    }
```

I would love to see the last example to be allowed: if @Optional is defined and there is no @Parameters for the method parameter handle it as if the parameter value is missing, thus using the @Optional value.

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes #564 .

### Did you remember to?

- [X] Add test case(s)
- [X] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
Please merge only after PR #1725 has been merged (because this PR basically piggies back on the JDK8 and test failure change mostly to do away with merge conflicts)

**Comment by krmahadevan** [comment]
@juherr @cbeust - This can now be reviewed and merged if all is well. I have rebased this branch off of master (which now contains JDK8 compliance changes).

**Review by cbeust — APPROVED** [review]
Feel free to merge whenever you're ready, @krmahadevan !

**Comment by krmahadevan** [comment]
@cbeust - Thanks for the fast approval. I merged it :) I am aiming for sending at least a couple more PRs today :)

**Pull request merged**
