### PR TITLE
SoftAssert now uses the same auto-generated message used by Assert.

### PR DESCRIPTION
**Pull request by draghuram**
The change brings SoftAssert's message semantics in line with those of Assert's as requested in issue #504.

### CODE REVIEW

**Comment by jrocketz** [comment]
It doesn't appear as though the fix solved the issue. Here is the code that I used to test:
```java
import org.testng.Assert;
import org.testng.annotations.*;
import org.testng.asserts.SoftAssert;

public class TestAssert {
	
	@Test
	public void TestHardAssertEquals() {
		Assert.assertEquals(0,1);
	}
	
	@Test
	public void TestHardAssertBoolean() {
		Assert.assertTrue(false);
	}
	
	@Test
	public void TestSoftAssertion() {
		SoftAssert softAssert = new SoftAssert();
		softAssert.assertEquals(0,1);
		softAssert.assertTrue(false);
        softAssert.assertAll();
	}
	
}
```
And this is the result:
```
TestHardAssertBoolean	java.lang.AssertionError: expected [true] but found [false]
TestHardAssertEquals	java.lang.AssertionError: expected [1] but found [0]
TestSoftAssertion	java.lang.AssertionError: The following asserts failed:
null, null
```
I am using the following version of TestNG:
```
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.8.21</version>
    <scope>test</scope>
</dependency> 
```

**Comment by cbeust** [comment]
That's the expected behavior of assertAll().

-- 
Cédric

**Comment by jrocketz** [comment]
draghuram commented on https://github.com/cbeust/testng/issues/504 that `assertAll()` was reporting the correct assert messages using the code that I posted.
```
FAILED: TestSoftAssertion
java.lang.AssertionError: The following asserts failed:
expected [1] but found [0], expected [true] but found [false]
```
I double-checked my Maven Repository and confirmed that I am using the latest TestNG build (6.8.21). I also opened up the `SoftAssert.class` from the `testng-6.8.21.jar` in Eclipse and verified that code change is there. Is there something else that I can do to verify that I am on the latest version of TestNG?

**Comment by draghuram** [comment]
Sorry. I don't know enough of Eclipse to suggest a method to resolve this problem but I still feel that it is a case of wrong TestNG version being used.

**Pull request merged**
