### PR TITLE
Hipster badges

### PR DESCRIPTION
**Pull request by juherr**

### CODE REVIEW

**Comment by cbeust** [comment]
Can you explain what this does exactly? :)

**Comment by juherr** [comment]
It gives quick and up-to-date view of some key technical information directly from the main github page. 
You can have a look from https://github.com/juherr/testng/tree/hipster-badges?files=1

**Comment by cbeust** [comment]
I see, that's cool. And the dependencies are way out of date :)

**Comment by juherr** [comment]
Just 2 more things:
* Currently, the link to versioneye is daily updated.  You can subscribe yourself to it and have a link updated by github hook ;
* I planned to add some information from sonarqube but I didn't find how for the moment.

**Pull request merged**
