### PR TITLE
Move Parser into being an internal API

### LINKED ISSUE #2549: Allow providing custom file name when parsing XML suite from a dynamically built content
### TestNG Version

The latest

### Expected behavior

There should be an API to add a custom name to the provided input stream, so exception message could specify "file name" appropriately

### Actual behavior

Currently, TestNG refers to a non-existing file `/home/runner/work/testng/testng/core/testng.xml`, and it is hard to tell where the file was generated.

```
TestNG > Regression2 > test.annotationtransformer.AnnotationTransformerTest > annotationTransformerInXmlShouldBeRun STANDARD_OUT
    [TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >" at the top of the suite file [/home/runner/work/testng/testng/core/testng.xml] otherwise TestNG may fail or not work as expected.
```

### Test case sample

```java
  @Test
  public void annotationTransformerInXmlShouldBeRun() throws Exception {
    String xml =
        "<suite name=\"SingleSuite\" >"
            + "  <listeners>"
            + "    <listener class-name=\"test.annotationtransformer.AnnotationTransformerInTestngXml\" />"
            + "  </listeners>"
            + "  <test enabled=\"true\" name=\"SingleTest\">"
            + "    <classes>"
            + "      <class name=\"test.annotationtransformer.AnnotationTransformerInTestngXml\" />"
            + "    </classes>"
            + "  </test>"
            + "</suite>";

    ByteArrayInputStream is = new ByteArrayInputStream(xml.getBytes());
    Collection<XmlSuite> suites = new Parser(is).parse();
```

### PR DESCRIPTION
**Pull request by krmahadevan**
Closes #2549

Fixes #2549  .

### Did you remember to?

- [ ] Add test case(s)
- [X] Update `CHANGES.txt`

This PR does not address the original issue which is to add a custom file name to the Parser constructor. This PR merely moves this class into the `internal` package so that its API is not part of the public contract.

### CODE REVIEW

**Review by juherr — COMMENTED** [review]
Is it possible to move the merge of this PR after the merge of #2564?
I fear a too difficult merge in the other case.

**Comment by krmahadevan** [comment]
@juherr - Sure. That's a valid concern. Any idea when would #2564 be wrapped up and merged ? I just started fixing issues because I had some time at my end.

I dont want defects to start getting piled up

**Comment by juherr** [comment]
Please rebase 🙏

**Comment by krmahadevan** [comment]
@juherr - I will fix this, update the PR and ping once done.

**Review by juherr — APPROVED** [review]

**Review by juherr — CHANGES_REQUESTED** [review]
All pipelines are failing

**Comment by krmahadevan** [comment]
> All pipelines are failing

How do I find out what is causing the failures. This stuff is new to me. Any help ?

I see this 

```
:testng-core:autostyleJavaCheck failure marker
  Error: Execution failed for task ':testng-core:autostyleJavaCheck':
      See 'What went wrong' below

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testng-core:autostyleJavaCheck'.
> The following files have format violations:
    testng-core/src/main/java/org/testng/Converter.java
      @@ -12,8 +12,8 @@
       import java.util.Set;
       import org.testng.collections.Sets;
       import org.testng.internal.Yaml;
      -import org.testng.xml.internal.Parser;
       import org.testng.xml.XmlSuite;
      +import org.testng.xml.internal.Parser;
```

@juherr  - can you please help me with the below questions ?

* What does this mean ?
* How do I fix this ?
* How can I ensure that I take care of this on my desktop itself ?

**Review by juherr — APPROVED** [review]

**Pull request merged**
