### PR TITLE
Generic assert

### PR DESCRIPTION
**Pull request by juherr**
Rework of asserts package

### CODE REVIEW

**Comment by cbeust** [comment]
I like this change but isn't it going to break everyone who is currently using IAssert?

**Comment by juherr** [comment]
It shouldn't as it will like they use raw types, and all was Object before. But I will add few tests to confirm.

**Comment by cbeust** [comment]
Yes, they should be warnings but let's tread very carefully here, tests
would be great.

-- 
Cédric

**Comment by juherr** [comment]
@cbeust Tests added. Are they enough for you?

**Comment by cbeust** [comment]
LGTM!

**Pull request merged**
