### PR TITLE
Add Guice Stage configuration for a suite

### PR DESCRIPTION
**Pull request by guillaumecle**
Patch for #663

### CODE REVIEW

**Comment by cbeust** [comment]
Thanks!

**Comment by cbeust** [comment]
@guillaumecle Could you please update the following files to document `guice-stage`?

- `doc/documentation-main.html`
- `src/main/resources/testng-1.0.dtd`

Thanks!

**Comment by guillaumecle** [comment]
#684 here it is. Tell me if I can improve it in anyway.
Sorry for the forgotten println.

PS: is http://testng.org/testng-1.0.dtd up to date the dtd of the release?

**Comment by cbeust** [comment]
Thanks, I made a few comments. Yes, the DTD is up to date so it only needs
your two additions.

-- 
Cédric

**Pull request merged**
